In [1]:
import pandas as pd
import numpy as np

In [2]:
O_2009 = pd.read_csv('data/2009.csv')
O_2009

,Team,Gms,TotÂ Pts,Pts/G,RushYds,RYds/G,PassYds,PYds/G,TotYds,Yds/G,year
0,New Orleans SaintsNew Orleans,16,510,31.9,2106,131.6,4355,272.2,6461,403.8,2009
1,Dallas CowboysDallas,16,361,22.6,2103,131.4,4287,267.9,6390,399.4,2009
2,New England PatriotsNew England,16,427,26.7,1921,120.1,4436,277.2,6357,397.3,2009
3,Houston TexansHouston,16,388,24.2,1475,92.2,4654,290.9,6129,383.1,2009
4,Minnesota VikingsMinnesota,16,470,29.4,1918,119.9,4156,259.8,6074,379.6,2009
5,Green Bay PackersGreen Bay,16,461,28.8,1885,117.8,4180,261.2,6065,379.1,2009
6,Pittsburgh SteelersPittsburgh,16,368,23.0,1793,112.1,4148,259.2,5941,371.3,2009
7,New York GiantsNY Giants,16,402,25.1,1837,114.8,4019,251.2,5856,366.0,2009
8,Indianapolis ColtsIndianapolis,16,416,26.0,1294,80.9,4515,282.2,5809,363.1,2009
9,San Diego ChargersSan Diego,16,454,28.4,1423,88.9,4338,271.1,5761,360.1,2009
10,Philadelphia EaglesPhiladelphia,16,429,26.8,1637,102.3,4089,255.6,5726,357.9,2009
11,Tennessee TitansTennessee,16,354,22.1,2592,162.0,3031,189.4,5623,351.4,2009
12,Baltimore RavensBaltimore,16,391,24.4,2200,137.5,3419,213.7,5619,351.2,2009
13,Arizona CardinalsArizona,16,375,23.4,1494,93.4,4016,251.0,5510,344.4,2009
14,Denver BroncosDenver,16,326,20.4,1836,114.8,3627,226.7,5463,341.4,2009
15,Atlanta FalconsAtlanta,16,363,22.7,1876,117.2,3571,223.2,5447,340.4,2009
16,Miami DolphinsMiami,16,360,22.5,2231,139.4,3170,198.1,5401,337.6,2009
17,Jacksonville JaguarsJacksonville,16,290,18.1,2029,126.8,3356,209.8,5385,336.6,2009
18,Carolina PanthersCarolina,16,315,19.7,2498,156.1,2799,174.9,5297,331.1,2009
19,New York JetsNY Jets,16,348,21.8,2756,172.2,2380,148.8,5136,321.0,2009
20,Seattle SeahawksSeattle,16,280,17.5,1566,97.9,3503,218.9,5069,316.8,2009
21,Washington RedskinsWashington,16,266,16.6,1510,94.4,3490,218.1,5000,312.5,2009
22,Chicago BearsChicago,16,327,20.4,1492,93.2,3473,217.1,4965,310.3,2009
23,Cincinnati BengalsCincinnati,16,305,19.1,2056,128.5,2890,180.6,4946,309.1,2009
24,Kansas City ChiefsKansas City,16,294,18.4,1929,120.6,2922,182.6,4851,303.2,2009
25,Detroit LionsDetroit,16,262,16.4,1616,101.0,3168,198.0,4784,299.0,2009
26,San Francisco 49ersSan Francisco,16,330,20.6,1600,100.0,3052,190.8,4652,290.8,2009
27,Tampa Bay BuccaneersTampa Bay,16,244,15.2,1627,101.7,2973,185.8,4600,287.5,2009
28,St. Louis RamsSt. Louis,16,175,10.9,1784,111.5,2686,167.9,4470,279.4,2009
29,Buffalo BillsBuffalo,16,258,16.1,1867,116.7,2515,157.2,4382,273.9,2009
30,Oakland RaidersOakland,16,197,12.3,1701,106.3,2557,159.8,4258,266.1,2009
31,Cleveland BrownsCleveland,16,245,15.3,2087,130.4,2076,129.8,4163,260.2,2009

In [3]:
filtered = O_2009[['year', 'Team', 'Pts/G', 'Yds/G']]

In [4]:
filtered.head()

   year                             Team  Pts/G  Yds/G
0  2009    New Orleans SaintsNew Orleans   31.9  403.8
1  2009             Dallas CowboysDallas   22.6  399.4
2  2009  New England PatriotsNew England   26.7  397.3
3  2009            Houston TexansHouston   24.2  383.1
4  2009       Minnesota VikingsMinnesota   29.4  379.6

In [5]:
filtered.rename(columns={"Pts/G": "O_Pts/G", "Yds/G": "O_Yds/G"})

    year                              Team  O_Pts/G  O_Yds/G
0   2009     New Orleans SaintsNew Orleans     31.9    403.8
1   2009              Dallas CowboysDallas     22.6    399.4
2   2009   New England PatriotsNew England     26.7    397.3
3   2009             Houston TexansHouston     24.2    383.1
4   2009        Minnesota VikingsMinnesota     29.4    379.6
5   2009        Green Bay PackersGreen Bay     28.8    379.1
6   2009     Pittsburgh SteelersPittsburgh     23.0    371.3
7   2009          New York GiantsNY Giants     25.1    366.0
8   2009    Indianapolis ColtsIndianapolis     26.0    363.1
9   2009       San Diego ChargersSan Diego     28.4    360.1
10  2009   Philadelphia EaglesPhiladelphia     26.8    357.9
11  2009         Tennessee TitansTennessee     22.1    351.4
12  2009         Baltimore RavensBaltimore     24.4    351.2
13  2009          Arizona CardinalsArizona     23.4    344.4
14  2009              Denver BroncosDenver     20.4    341.4
15  2009            Atlanta FalconsAtlanta     22.7    340.4
16  2009               Miami DolphinsMiami     22.5    337.6
17  2009  Jacksonville JaguarsJacksonville     18.1    336.6
18  2009         Carolina PanthersCarolina     19.7    331.1
19  2009              New York JetsNY Jets     21.8    321.0
20  2009           Seattle SeahawksSeattle     17.5    316.8
21  2009     Washington RedskinsWashington     16.6    312.5
22  2009              Chicago BearsChicago     20.4    310.3
23  2009      Cincinnati BengalsCincinnati     19.1    309.1
24  2009     Kansas City ChiefsKansas City     18.4    303.2
25  2009              Detroit LionsDetroit     16.4    299.0
26  2009  San Francisco 49ersSan Francisco     20.6    290.8
27  2009     Tampa Bay BuccaneersTampa Bay     15.2    287.5
28  2009           St. Louis RamsSt. Louis     10.9    279.4
29  2009              Buffalo BillsBuffalo     16.1    273.9
30  2009            Oakland RaidersOakland     12.3    266.1
31  2009         Cleveland BrownsCleveland     15.3    260.2

In [6]:
Offense_2009 = filtered

In [7]:
Defense_2009 = pd.read_csv('data/2009_Update.csv')
Defense_2009.head()

,Team,Gms,TotÂ Pts,Pts/G,RushYds,RYds/G,PassYds,PYds/G,TotYds,Yds/G,year,Playoff
0,New York JetsNY Jets,16,236,14.8,1578,98.6,2459,153.7,4037,252.3,2009,False
1,Green Bay PackersGreen Bay,16,297,18.6,1333,83.3,3218,201.1,4551,284.4,2009,True
2,Baltimore RavensBaltimore,16,261,16.3,1492,93.2,3316,207.2,4808,300.5,2009,True
3,Cincinnati BengalsCincinnati,16,291,18.2,1573,98.3,3249,203.1,4822,301.4,2009,True
4,Pittsburgh SteelersPittsburgh,16,324,20.2,1438,89.9,3447,215.4,4885,305.3,2009,True

In [8]:
filtered_d = Defense_2009[['year', 'Team', 'Pts/G', 'Yds/G', 'Playoff']]

In [9]:
Defense_2009 = filtered_d.rename(columns={"Pts/G": "D_Pts/G", "Yds/G": "D_Yds/G"})

In [10]:
Defense_2009

    year                              Team  D_Pts/G  D_Yds/G  Playoff
0   2009              New York JetsNY Jets     14.8    252.3    False
1   2009        Green Bay PackersGreen Bay     18.6    284.4     True
2   2009         Baltimore RavensBaltimore     16.3    300.5     True
3   2009      Cincinnati BengalsCincinnati     18.2    301.4     True
4   2009     Pittsburgh SteelersPittsburgh     20.2    305.3     True
5   2009        Minnesota VikingsMinnesota     19.5    305.5    False
6   2009              Denver BroncosDenver     20.2    315.0    False
7   2009         Carolina PanthersCarolina     19.2    315.8    False
8   2009              Dallas CowboysDallas     15.6    315.9     True
9   2009     Washington RedskinsWashington     21.0    319.7     True
10  2009   New England PatriotsNew England     17.8    320.2    False
11  2009   Philadelphia EaglesPhiladelphia     21.1    321.1     True
12  2009             Houston TexansHouston     20.8    324.9    False
13  2009          New York GiantsNY Giants     26.7    324.9     True
14  2009  San Francisco 49ersSan Francisco     17.6    326.4    False
15  2009       San Diego ChargersSan Diego     20.0    327.0     True
16  2009              Chicago BearsChicago     23.4    337.8    False
17  2009    Indianapolis ColtsIndianapolis     19.2    339.2    False
18  2009              Buffalo BillsBuffalo     20.4    340.6    False
19  2009          Arizona CardinalsArizona     20.3    346.4     True
20  2009            Atlanta FalconsAtlanta     20.3    348.9    False
21  2009               Miami DolphinsMiami     24.4    349.3    False
22  2009  Jacksonville JaguarsJacksonville     23.8    352.3    False
23  2009           Seattle SeahawksSeattle     24.4    356.4    False
24  2009     New Orleans SaintsNew Orleans     21.3    357.8     True
25  2009            Oakland RaidersOakland     23.7    361.9    False
26  2009     Tampa Bay BuccaneersTampa Bay     25.0    365.6     True
27  2009         Tennessee TitansTennessee     25.1    365.6    False
28  2009           St. Louis RamsSt. Louis     27.2    372.8    False
29  2009     Kansas City ChiefsKansas City     26.5    388.2    False
30  2009         Cleveland BrownsCleveland     23.4    389.3    False
31  2009              Detroit LionsDetroit     30.9    392.1    False

In [12]:
frames = [Defense_2009, Offense_2009]
Defense_2009.shape, Offense_2009.shape

((32, 5), (32, 4))

In [14]:
merge_2009 = pd.merge(Defense_2009, Offense_2009)

In [15]:
merge_2009

,year,Team,D_Pts/G,D_Yds/G,Playoff,Pts/G,Yds/G
0,2009,New York JetsNY Jets,14.8,252.3,False,21.8,321.0
1,2009,Green Bay PackersGreen Bay,18.6,284.4,True,28.8,379.1
2,2009,Baltimore RavensBaltimore,16.3,300.5,True,24.4,351.2
3,2009,Cincinnati BengalsCincinnati,18.2,301.4,True,19.1,309.1
4,2009,Pittsburgh SteelersPittsburgh,20.2,305.3,True,23.0,371.3
5,2009,Minnesota VikingsMinnesota,19.5,305.5,False,29.4,379.6
6,2009,Denver BroncosDenver,20.2,315.0,False,20.4,341.4
7,2009,Carolina PanthersCarolina,19.2,315.8,False,19.7,331.1
8,2009,Dallas CowboysDallas,15.6,315.9,True,22.6,399.4
9,2009,Washington RedskinsWashington,21.0,319.7,True,16.6,312.5
10,2009,New England PatriotsNew England,17.8,320.2,False,26.7,397.3
11,2009,Philadelphia EaglesPhiladelphia,21.1,321.1,True,26.8,357.9
12,2009,Houston TexansHouston,20.8,324.9,False,24.2,383.1
13,2009,New York GiantsNY Giants,26.7,324.9,True,25.1,366.0
14,2009,San Francisco 49ersSan Francisco,17.6,326.4,False,20.6,290.8
15,2009,San Diego ChargersSan Diego,20.0,327.0,True,28.4,360.1
16,2009,Chicago BearsChicago,23.4,337.8,False,20.4,310.3
17,2009,Indianapolis ColtsIndianapolis,19.2,339.2,False,26.0,363.1
18,2009,Buffalo BillsBuffalo,20.4,340.6,False,16.1,273.9
19,2009,Arizona CardinalsArizona,20.3,346.4,True,23.4,344.4
20,2009,Atlanta FalconsAtlanta,20.3,348.9,False,22.7,340.4
21,2009,Miami DolphinsMiami,24.4,349.3,False,22.5,337.6
22,2009,Jacksonville JaguarsJacksonville,23.8,352.3,False,18.1,336.6
23,2009,Seattle SeahawksSeattle,24.4,356.4,False,17.5,316.8
24,2009,New Orleans SaintsNew Orleans,21.3,357.8,True,31.9,403.8
25,2009,Oakland RaidersOakland,23.7,361.9,False,12.3,266.1
26,2009,Tampa Bay BuccaneersTampa Bay,25.0,365.6,True,15.2,287.5
27,2009,Tennessee TitansTennessee,25.1,365.6,False,22.1,351.4
28,2009,St. Louis RamsSt. Louis,27.2,372.8,False,10.9,279.4
29,2009,Kansas City ChiefsKansas City,26.5,388.2,False,18.4,303.2
30,2009,Cleveland BrownsCleveland,23.4,389.3,False,15.3,260.2
31,2009,Detroit LionsDetroit,30.9,392.1,False,16.4,299.0